INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('1', 'SRVT2WP', '10.33.1.221', '19', 'Worker process (Intégration des commande web thirard,fernand, beaurain)', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('2', 'SRVY2ARR', '10.33.1.217', '19', '', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('3', 'SRVY2IISA', '10.33.1.216', '19', '', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('4', 'SRVY2IISB', '10.33.1.215', '19', '', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('5', 'SRVT2SMTP', '10.33.1.209', '19', 'Serveur de mail', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('6', 'SRVT2EB1', '10.33.1.111', '19', 'Serveur AD, DHCP, DNS et temp', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('7', 'SRVT2FS', '10.33.1.223', '19', 'Serveur de fichier', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('8', 'SRVY2SQL', '10.33.1.252', '19', 'Serveur de BDD SQL Server', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('9', 'SRVY2RAD', '10.33.1.214', '19', 'Radio', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('10', 'SRVY2RPT', '10.33.1.213', '19', 'Reporting', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('11', 'SRVY2WP', '10.33.1.212', '19', 'Worker process Y2 (gère les gros traitement)', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('12', 'SRVT2EB2', '10.33.1.117', '19', 'Serveur AD, DHCP, DNS et temp', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('13', 'SRVT2ETL', '10.33.1.225', '19', 'SRV de test ETL', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('14', 'SRVT2OXO', '10.33.1.224', '19', 'Serveur de gestion de la téléphonie IP', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('15', 'SRVT2RDS', '10.33.1.222', '19', 'Serveur de bureau à distance', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('16', 'SRVT2ST', '10.33.1.228', '19', '', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('17', 'VMCOMMUNICATION', '10.33.1.132', '16', 'api web d''intération dans prestashop', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('18', 'VMAUTOMATISME', '10.33.1.130', '16', 'génération facture, impression...', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('19', 'VMBOA', '10.33.1.131', '16', 'Chaine logistique BOA', '0');
INSERT INTO "main"."server" ("id", "name", "ip", "version", "description", "rebootrequired") VALUES ('20', 'SRVT2SV', '10.33.1.99', '19', 'Serveur de supervision (Grafana, suivi des MAJ...)', '1');